//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALRSM.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALRSM.Resources.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient already exists..
        /// </summary>
        public static string DuplicatePatientId {
            get {
                return ResourceManager.GetString("DuplicatePatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id or password is invalid..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exam step..
        /// </summary>
        public static string InvalidExamStep {
            get {
                return ResourceManager.GetString("InvalidExamStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of ExamStep is invalid..
        /// </summary>
        public static string InvalidExamStepDescription {
            get {
                return ResourceManager.GetString("InvalidExamStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date is invalid..
        /// </summary>
        public static string InvalidExamStepEndDate {
            get {
                return ResourceManager.GetString("InvalidExamStepEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial date is invalid..
        /// </summary>
        public static string InvalidExamStepInitialDate {
            get {
                return ResourceManager.GetString("InvalidExamStepInitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of ExamStep is invalid..
        /// </summary>
        public static string InvalidExamStepState {
            get {
                return ResourceManager.GetString("InvalidExamStepState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time..
        /// </summary>
        public static string InvalidExamStepTime {
            get {
                return ResourceManager.GetString("InvalidExamStepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientId is invalid..
        /// </summary>
        public static string InvalidPatientId {
            get {
                return ResourceManager.GetString("InvalidPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point is invalid..
        /// </summary>
        public static string InvalidPoint {
            get {
                return ResourceManager.GetString("InvalidPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer is invalid..
        /// </summary>
        public static string InvalidSecurityAnswer {
            get {
                return ResourceManager.GetString("InvalidSecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security question is invalid..
        /// </summary>
        public static string InvalidSecurityQuestion {
            get {
                return ResourceManager.GetString("InvalidSecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is invalid..
        /// </summary>
        public static string InvalidUserConfirmPassword {
            get {
                return ResourceManager.GetString("InvalidUserConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id is invalid..
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only patients has exams..
        /// </summary>
        public static string InvalidUserIdForExams {
            get {
                return ResourceManager.GetString("InvalidUserIdForExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is invalid..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is invalid..
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the password must be between 6 and 20..
        /// </summary>
        public static string InvalidUserPasswordLength {
            get {
                return ResourceManager.GetString("InvalidUserPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords does not match..
        /// </summary>
        public static string PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
