//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALSRM.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALSRM.WebApp.Resources.AboutResources", typeof(AboutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since it does not exist yet, cure for ALS, so there is a need to monitor patients, so that you can observe the evolution of the disease. Since the evolution of the disease is different in each case, it is important to follow up the patient and thus intervene in good time in every situation. As such was desenvolvivda a mobile application (Android) able to monitor the patient, but the same feel comfortable with this monitoring, it can achieve it in the comfort of your home. The mobile application has been dev [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppMobileText {
            get {
                return ResourceManager.GetString("AppMobileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to provide more convenience to the patient of ALS, the current web application was developed, that has the same make various query means related to their exams. He always tried to develop an application more intuitive and fluid as possible. It was also developed this application an area for the doctor, so that it can register new patients, schedule new exams and make a manage them simply. This area has as a future objective of its association with the application already developed &lt;a href=&quot;http://p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppWebText {
            get {
                return ResourceManager.GetString("AppWebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amyotrophic Lateral Sclerosis.
        /// </summary>
        public static string Ela {
            get {
                return ResourceManager.GetString("Ela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amyotrophic Lateral Sclerosis (ALS) is a degenerative neurological disease, progressive and fatal. Motor neurons, which receive electrical stimuli are primarily those who send the message to the muscle so there is excitement and contraction, i.e. control voluntary muscle movements. With the progress of the disease the muscles die early and as a result the ALS patient starts to lose their physical abilities..
        /// </summary>
        public static string ElaText {
            get {
                return ResourceManager.GetString("ElaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Application.
        /// </summary>
        public static string MobileApp {
            get {
                return ResourceManager.GetString("MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Api.
        /// </summary>
        public static string WebApi {
            get {
                return ResourceManager.GetString("WebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a connection between doctor and patient was possible a data access interface, able to communicate with any type of application it was developed. For example this interface provides the patient exams you need to perform and after conducting the examination the related information will be made available to the physician..
        /// </summary>
        public static string WebApiText {
            get {
                return ResourceManager.GetString("WebApiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Application.
        /// </summary>
        public static string WebApp {
            get {
                return ResourceManager.GetString("WebApp", resourceCulture);
            }
        }
    }
}
